In [2]:
import numpy as np

In [3]:
Distance = [14, 525, 62, 87]
Time = [10, 38, 89, 63]

In [4]:
Speed = Distance / Time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
distance = np.array(Distance)
time = np.array(Time)

In [6]:
Speed = distance / time
print(Speed)

[ 1.4        13.81578947  0.69662921  1.38095238]


In [7]:
City = np.array(["NYC", "LDN", "MIAMI", "DALLAS"])
CityWithState = np.array([["NYC", "LDN", "MIMI", "DLS"], ["NEW YORK", "LONDON", "MIAMI", "DALLAS"]])
print(City.ndim, CityWithState.ndim)

1 2


In [8]:
print(City.shape, CityWithState.shape)

(4,) (2, 4)


In [9]:
print(CityWithState.size, City.size)

8 4


In [10]:
City.dtype

dtype('<U6')

In [11]:
print(distance % time)

[ 4 31 62 24]


In [12]:
print(distance[0::1])

[ 14 525  62  87]


In [13]:
distance, time

(array([ 14, 525,  62,  87]), array([10, 38, 89, 63]))

In [14]:
score = distance > 60

In [15]:
distance != None

array([ True,  True,  True,  True])

In [16]:
distance_view = distance.view()
print(distance_view, len(distance_view))

[ 14 525  62  87] 4


In [17]:
distance_view[2] = 250
print(distance_view, distance)

[ 14 525 250  87] [ 14 525 250  87]


In [18]:
distance_deepcopy = distance.copy()
print(distance_deepcopy, distance)

[ 14 525 250  87] [ 14 525 250  87]


In [19]:
distance_deepcopy[2] = 62
print(distance_deepcopy, distance)

[ 14 525  62  87] [ 14 525 250  87]


In [20]:
New_Cyclist_Trials = np.array([[67, 32, 96, 41, 70, 85], [12, 43, 96, 753, 298, 39]])
print(New_Cyclist_Trials.ndim)

2


In [21]:
New_Cyclist_Trials.ravel()

array([ 67,  32,  96,  41,  70,  85,  12,  43,  96, 753, 298,  39])

In [22]:
New_Cyclist_Trials.reshape(12, 1)

array([[ 67],
       [ 32],
       [ 96],
       [ 41],
       [ 70],
       [ 85],
       [ 12],
       [ 43],
       [ 96],
       [753],
       [298],
       [ 39]])

In [23]:
Week_1 = np.array([73, 86, 23, 0, 914])
Week_2 = np.array([32, 94, 72, 27, 95])

In [24]:
Total_Earning = Week_1 + Week_2
print(Total_Earning)

[ 105  180   95   27 1009]


In [25]:
Week_1 = Week_1 / 10
print(Week_1)

[ 7.3  8.6  2.3  0.  91.4]


In [26]:
Week_1 = np.array([[73, 86, 23, 0, 914], [32, 94, 72, 27, 95]])
print(Week_1)

[[ 73  86  23   0 914]
 [ 32  94  72  27  95]]


In [27]:
print(Week_1.transpose())

[[ 73  32]
 [ 86  94]
 [ 23  72]
 [  0  27]
 [914  95]]
